export const countries = [
  { code: "US", name: "United States", dial: "+1", pos: -44 },
  { code: "IN", name: "India", dial: "+91", pos: -1694 },
  { code: "AF", name: "Afghanistan", dial: "+93", pos: -2311 },
  { code: "AL", name: "Albania", dial: "+355", pos: -1034 },
  { code: "DZ", name: "Algeria", dial: "+213", pos: -528 },
  { code: "AS", name: "American Samoa", dial: "+1684", pos: -1562 },
  { code: "AD", name: "Andorra", dial: "+376", pos: -594 },
  { code: "AO", name: "Angola", dial: "+244", pos: -1947 },
  { code: "AI", name: "Anguilla", dial: "+1264", pos: -1980 },
  { code: "AG", name: "Antigua and Barbuda", dial: "+1268", pos: -869 },
  { code: "AR", name: "Argentina", dial: "+54", pos: -2377 },
  { code: "AM", name: "Armenia", dial: "+374", pos: -176 },
  { code: "AW", name: "Aruba", dial: "+297", pos: -792 },
  { code: "AU", name: "Australia", dial: "+61", pos: -1716 },
  { code: "AT", name: "Austria", dial: "+43", pos: -1331 },
  { code: "AZ", name: "Azerbaijan", dial: "+994", pos: -1243 },
  { code: "BS", name: "Bahamas", dial: "+1242", pos: -363 },
  { code: "BH", name: "Bahrain", dial: "+973", pos: -1496 },
  { code: "BD", name: "Bangladesh", dial: "+880", pos: -1771 },
  { code: "BB", name: "Barbados", dial: "+1246", pos: -1573 },
  { code: "BY", name: "Belarus", dial: "+375", pos: -1100 },
  { code: "BE", name: "Belgium", dial: "+32", pos: 0 },
  { code: "BZ", name: "Belize", dial: "+501", pos: -484 },
  { code: "BJ", name: "Benin", dial: "+229", pos: -1298 },
  { code: "BM", name: "Bermuda", dial: "+1441", pos: -1914 },
  { code: "BT", name: "Bhutan", dial: "+975", pos: -1848 },
  { code: "BO", name: "Bolivia", dial: "+591", pos: -1650 },
  { code: "BA", name: "Bosnia and Herzegovina", dial: "+387", pos: -1584 },
  { code: "BW", name: "Botswana", dial: "+267", pos: -2707 },
  { code: "BR", name: "Brazil", dial: "+55", pos: -770 },
  { code: "BN", name: "Brunei", dial: "+673", pos: -1683 },
  { code: "BG", name: "Bulgaria", dial: "+359", pos: -2586 },
  { code: "KH", name: "Cambodia", dial: "+855", pos: -242 },
  { code: "CM", name: "Cameroon", dial: "+237", pos: -2057 },
  { code: "CA", name: "Canada", dial: "+1", pos: -1375 },
  { code: "CL", name: "Chile", dial: "+56", pos: -1342 },
  { code: "CN", name: "China", dial: "+86", pos: -825 },
  { code: "CO", name: "Colombia", dial: "+57", pos: -330 },
  { code: "CR", name: "Costa Rica", dial: "+506", pos: -2090 },
  { code: "HR", name: "Croatia", dial: "+385", pos: -902 },
  { code: "CU", name: "Cuba", dial: "+53", pos: -748 },
  { code: "CY", name: "Cyprus", dial: "+357", pos: -561 },
  { code: "CZ", name: "Czech Republic", dial: "+420", pos: -2256 },
  { code: "DK", name: "Denmark", dial: "+45", pos: -1386 },
  { code: "EG", name: "Egypt", dial: "+20", pos: -2201 },
  { code: "EE", name: "Estonia", dial: "+372", pos: -2410 },
  { code: "FI", name: "Finland", dial: "+358", pos: -1903 },
  { code: "FR", name: "France", dial: "+33", pos: -1012 },
  { code: "DE", name: "Germany", dial: "+49", pos: -2509 },
  { code: "GR", name: "Greece", dial: "+30", pos: -165 },
  { code: "HK", name: "Hong Kong", dial: "+852", pos: -2696 },
  { code: "HU", name: "Hungary", dial: "+36", pos: -682 },
  { code: "IS", name: "Iceland", dial: "+354", pos: -1991 },
  { code: "ID", name: "Indonesia", dial: "+62", pos: -1958 },
  { code: "IR", name: "Iran", dial: "+98", pos: -2013 },
  { code: "IE", name: "Ireland", dial: "+353", pos: -1969 },
  { code: "IL", name: "Israel", dial: "+972", pos: -341 },
  { code: "IT", name: "Italy", dial: "+39", pos: -143 },
  { code: "JP", name: "Japan", dial: "+81", pos: -429 },
  { code: "KE", name: "Kenya", dial: "+254", pos: -2630 },
  { code: "KR", name: "South Korea", dial: "+82", pos: -2245 },
  { code: "KW", name: "Kuwait", dial: "+965", pos: -2487 },
  { code: "MY", name: "Malaysia", dial: "+60", pos: -1870 },
  { code: "MX", name: "Mexico", dial: "+52", pos: -2024 },
  { code: "NP", name: "Nepal", dial: "+977", pos: -110 },
  { code: "NL", name: "Netherlands", dial: "+31", pos: -1441 },
  { code: "NZ", name: "New Zealand", dial: "+64", pos: -1540 },
  { code: "NG", name: "Nigeria", dial: "+234", pos: -2476 },
  { code: "NO", name: "Norway", dial: "+47", pos: -836 },
  { code: "PK", name: "Pakistan", dial: "+92", pos: -2035 },
  { code: "PH", name: "Philippines", dial: "+63", pos: -1815 },
  { code: "PL", name: "Poland", dial: "+48", pos: -1177 },
  { code: "PT", name: "Portugal", dial: "+351", pos: -517 },
  { code: "QA", name: "Qatar", dial: "+974", pos: -462 },
  { code: "RO", name: "Romania", dial: "+40", pos: -671 },
  { code: "RU", name: "Russia", dial: "+7", pos: -660 },
  { code: "SA", name: "Saudi Arabia", dial: "+966", pos: -33 },
  { code: "SG", name: "Singapore", dial: "+65", pos: -22 },
  { code: "ZA", name: "South Africa", dial: "+27", pos: -2355 },
  { code: "ES", name: "Spain", dial: "+34", pos: -1155 },
  { code: "LK", name: "Sri Lanka", dial: "+94", pos: -2641 },
  { code: "SE", name: "Sweden", dial: "+46", pos: -385 },
  { code: "CH", name: "Switzerland", dial: "+41", pos: -1320 },
  { code: "TH", name: "Thailand", dial: "+66", pos: -957 },
  { code: "TR", name: "Turkey", dial: "+90", pos: -1606 },
  { code: "UA", name: "Ukraine", dial: "+380", pos: -2002 },
  { code: "AE", name: "United Arab Emirates", dial: "+971", pos: -2223 },
  { code: "GB", name: "United Kingdom", dial: "+44", pos: -55 },
  { code: "VN", name: "Vietnam", dial: "+84", pos: -968 },
  { code: "ZW", name: "Zimbabwe", dial: "+263", pos: -2046 }
];
